deployment:
  deploymentName: wordpress
  image:
    repository: wordpress
  imageTag: 4.8-apache
  dbHost: mysql
  secretName: mysql-pass
  secretNameKey: password

service:
  serviceName: mysql

statefulSet:
  #statefulSetName: mysql
  imageRepository:  mysql
  image:
    repository: mysql
    tag: 5.6
  secretNameKey: password

service:
  serviceName: nodeport-service
  serviceType: NodePort

secret:
  secretName: mysql-pass
  password: MySecurePas55

ingress:
  ingressName: tls-ingress
  ingressSecret: ingress-tls-secret
