apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: {{.Values.service.name}}
spec:
  type: {{.Values.service.type}}
  ports:
  - nodePort: 31920
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend
