apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Chart.Name}} 
  labels:
    app: {{.Chart.Name}}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: {{.Values.wordpress.repository}}:{{.Values.wordpress.tag}}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{.Values.DbHost}}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.SecretName}}
              key: {{.Values.SecretNameKey}}
        ports:
        - containerPort: 80
          name: wordpress
        securityContext:
          allowPrivilegeEscalation: false
