apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.IngressName}}
spec:
  tls:
  - secretName: {{.Values.IngressSecret}}
  backend:
    serviceName: nodeport-service
    servicePort: 80
